# Generated by Django 3.2.7 on 2021-09-10 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YearModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.yearmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_num', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('total_num', models.FloatField()),
                ('grade', models.CharField(max_length=2)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subjectmodel')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.yearmodel')),
            ],
            options={
                'ordering': ['registration_num'],
            },
        ),
    ]
